name: Decreption
on: push


jobs:

  decrypt:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v1

      - name: decrypt file

        run: gpg --quiet --batch --yes --decrypt

          --passphrase="$PASSPHRASE" --output $HOME/source.txt

          source.txt.gpg

        env:

          PASSPHRASE: ${{ secrets.PASSPHRASE }}

      - name: print file

        run: cat $HOME/source.txt