name: dispatch receiver

on: 
    repository_dispatch:
        type: choice
        description: Deploy from branch/tag
        required: true
        options:
        - true
        - false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: dispatch trigger
      if: github.event.action == "YOUR_EVENT_TYPE"
      run: |
        echo "repository_dispatch triggered"
