name: Container

on: repository_dispatch

jobs:
   docker-steps:
     runs-on: ubuntu-latest
     container:
       image: node:10.18.0-jessie
     steps:
        - name: Log node version
          run: node -v  
        - name: Steps with docker
          uses: docker://node:12.14.1-alpine3.10
          with: 
            entrypoint: "/bin/echo"
            args: "Hello World"
        - name: Log Node Version
          uses: docker://node:12.14.1-alpine3.10
          with: 
            entrypoint: /usr/local/bin/node
            args: -v
        - uses: actions/checkout@v1    
        - name: Change permissions
          run : chmod +x script.sh
        - name: Run a script
          uses: docker://node:12.14.1-alpine3.10
          with: 
            entrypoint: ./script.sh
            args: "ABC XYZ LMN"    
