name: Shell Commands

on: [push]

jobs: 
   runs-on: ubuntu-lastest
   steps:
     - name: echo a string

       run: echo "Hello"

     - name: multiline script
       
       run: |

        node -v
        npm -v