name: Shell Commands

on: [pull_request]

jobs: 
   runs-on: windows-latest
   steps:
     - name: echo a string
       run: echo "Hello"
     - name: multiline script
       run: |
        ls
        node -v
        npm -v
    