name: Shell Commands

on: [push]

jobs: 
   run-on: windows 10
   steps:
     - name: echo a string

       run: echo "Hello"

     - name: multiline script
       
       run: |

        node -v
        npm -v