name: Shell Commands

on: [push]

jobs: 
  cypress-run:
   runs-on: windows-lastest
   steps:
     - name: echo a string

       run: echo "Hello"

     - name: multiline script
       
       run: |

        node -v
        npm -v
    