name: ENV Vaiables



on: [push]

 

jobs:

  greeting_job:

    runs-on: ubuntu-latest

    env:

      Greeting: Hello

      First_Name: Mona

     

    steps:

      - name: "Say Hello Mona it's Monday"

        run: echo "$Greeting ${First_Name}. Today is ${{ secrets.WF_ENV}}!"